language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t erika/react-test -f ./client/Dockerfile.dev ./client

script:
#  - docker run -e CI=true USERNAME/react-test npm test
  - docker run erika/react-test npm test -- --coverage

after_sucess:
  - docker build -t erika/multi-client ./client
  - docker build -t erika/multi-nginx ./nginx
  - docker build -t erika/multi-server ./server
  - docker build -t erika/multi-worker ./worker
  # log in to the docker CLI 
  - echo "$DOCKER_PASSWORD"| docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push erika/multi-client
  - docker push erika/multi-nginx
  - docker push erika/multi-server
  - docker push erika/multi-worker

#deploy:
#  provider: elasticbeanstalk
#  region: us-west-1
#  app: multi-docker
#  env: MultiDocker-env
#  bucket_name: elasticbeanstalk-us-west-1-1234567890123
#  bucket_path: docker-multi
#  on:
#    branch: master
#  access_key_id: $AWS_ACCESS_KEY
#  secret_access_key:
#    secure: $AWS_SECRET_KEY
